language: python
sudo: false
before_install:
- pip install awscli --ignore-installed six
- aws --version
deploy:
  provider: s3
  access_key_id: AKIAIKXX3RHF6UIZSI6Q
  secret_access_key:
    secure: l/ASCLmS4kVyZCp2MNn9r3P5ijnyR89DR12P7NvaBED22eLeYFXgR7a4YPCKY2LeM1vd3Y0OJVRvj5vgW2OxPaR/A5cDD4kB19cSrT29wMSgO4L+qhrXkKQh7BisHtxK0BEwiFkUC2khYZ141kD1/0Qvj9bByQWCChFkiM95nWJ9e1IIvwOxS1NMwwLBpwt0ixD3P7xuLrfnalDAi1okYJSsELQRO3F1kX0EZtNRhmjfegaGPoEaBfHOUjFtS5oielm0p76AMXLhMPq4+t17Qp3ISiuvDiK7xi0bakIgMq43bhuO8saBnhpVL2kvDJ518TD8jX8SAiMcMijmQlyiWUtG0LvWLerM9eLJOM7Xtzy26QaVOG274xQGW+SeoKYGJRnOcmxYq1/UuF41JawkgOOc49Q82GKfrLKpaUgmUA5Vx1UicI2LecP8wcjuAnYyIGaeVvUUnl14m1YtUmSUjvxickejehtfJr436Pc2gulwUOGh7I/w18hdWu6U9gXxvR1GJMU+QI5HN2RpCa38dq+xGSzXwdztenvqzWX8a8ZMuVNSXbi6O3gXsHJDtdZhxGffnXropaLZVjHuY5BrDKeqPv0CVgs6nttw8TKSfd8ypdGYUPP76ENhaV60Ulcy3Ao8hdGaLpcv2Sv19TAtsaPk9uVFLrxd6YK3XtHSnaw=
  bucket: cdn.example.jp
  acl: public_read
  skip_cleanup: true
  on:
    repo: k-kinzal/cdn-integration-sample
after_success:
  - aws create-invalidation --distribution-id E109EQDT2BCAV0 --paths /*